name: flutter_media_storage
description: "Un package Flutter pour télécharger, stocker et afficher des médias localement."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

  # Gestion du stockage local
  hive_flutter: ^1.1.0
  hive: ^2.2.3  # Déplace ceci ici !
  path_provider: ^2.1.2

  # Téléchargement des fichiers
  dio: ^5.4.1

  # Gestion des images en cache
  cached_network_image: ^3.3.1

  # Lecture des vidéos locales
  video_player: ^2.8.2
  file_selector_linux: ^0.9.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Génération des adaptateurs Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.8