name: chat_app
description: "A new Flutter project."

# Empêche la publication sur pub.dev
publish_to: 'none'

# Version de l'application
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# Dépendances principales
dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.0.0
  font_awesome_flutter: ^10.0.0  
  flutter_media_storage:
    path: /home/maken/Documents/maken/package/flutter_media_storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.7 # Version compatible avec SDK 34
  path_provider: ^2.0.11 # Version compatible avec SDK 34
  video_player: ^2.5.0 # Version compatible avec SDK 34 (si utilisé)
  permission_handler: ^11.4.0


# Dépendances de développement
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0

# Configuration spécifique à Flutter
flutter:
  uses-material-design: true